export interface SourceCodeProduct {
  id: string;
  slug: string;
  title: string;
  description: string;
  shortDescription: string;
  price: number;
  originalPrice?: number;
  category: string;
  technologies: string[];
  rating: number;
  reviewCount: number;
  downloadCount: number;
  version: string;
  lastUpdated: string;
  author: {
    name: string;
    avatar: string;
  };
  thumbnail: string;
  featured: boolean;
  isNew: boolean;
  isBestseller: boolean;
}

export const sourceCodeProducts: SourceCodeProduct[] = [
  {
    id: "1",
    slug: "nextjs-saas-starter",
    title: "Next.js SaaS Starter Kit",
    description: "A production-ready SaaS boilerplate with authentication, billing, dashboard, and more. Built with Next.js 14, Prisma, and Stripe.",
    shortDescription: "Full-featured SaaS boilerplate with auth, billing, and dashboard.",
    price: 79,
    originalPrice: 129,
    category: "Boilerplates",
    technologies: ["Next.js", "TypeScript", "Prisma", "Stripe", "Tailwind"],
    rating: 4.9,
    reviewCount: 234,
    downloadCount: 1847,
    version: "2.1.0",
    lastUpdated: "2024-12-10",
    author: { name: "FlexStudio Team", avatar: "FS" },
    thumbnail: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=600&h=400&fit=crop&q=80",
    featured: true,
    isNew: false,
    isBestseller: true,
  },
  {
    id: "2",
    slug: "react-dashboard-admin",
    title: "React Dashboard Admin Pro",
    description: "A comprehensive admin dashboard with 50+ components, charts, tables, and real-time data visualization.",
    shortDescription: "Complete admin dashboard with 50+ UI components and charts.",
    price: 49,
    category: "Dashboards",
    technologies: ["React", "TypeScript", "Recharts", "Tailwind"],
    rating: 4.8,
    reviewCount: 189,
    downloadCount: 2341,
    version: "3.0.2",
    lastUpdated: "2024-12-08",
    author: { name: "FlexStudio Team", avatar: "FS" },
    thumbnail: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&h=400&fit=crop&q=80",
    featured: true,
    isNew: false,
    isBestseller: true,
  },
  {
    id: "3",
    slug: "nextjs-ecommerce-store",
    title: "Next.js E-Commerce Store",
    description: "Full-featured e-commerce solution with product management, cart, checkout, and Stripe integration.",
    shortDescription: "Complete e-commerce solution with Stripe payments.",
    price: 69,
    originalPrice: 99,
    category: "E-Commerce",
    technologies: ["Next.js", "TypeScript", "Stripe", "Prisma", "PostgreSQL"],
    rating: 4.7,
    reviewCount: 156,
    downloadCount: 1293,
    version: "1.8.0",
    lastUpdated: "2024-12-05",
    author: { name: "FlexStudio Team", avatar: "FS" },
    thumbnail: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=600&h=400&fit=crop&q=80",
    featured: true,
    isNew: false,
    isBestseller: false,
  },
  {
    id: "4",
    slug: "nodejs-rest-api",
    title: "Node.js REST API Starter",
    description: "Production-ready REST API with authentication, rate limiting, caching, and comprehensive documentation.",
    shortDescription: "Robust REST API with auth, caching, and documentation.",
    price: 39,
    category: "APIs",
    technologies: ["Node.js", "Express", "MongoDB", "Redis", "JWT"],
    rating: 4.8,
    reviewCount: 142,
    downloadCount: 1876,
    version: "2.3.1",
    lastUpdated: "2024-12-01",
    author: { name: "FlexStudio Team", avatar: "FS" },
    thumbnail: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=600&h=400&fit=crop&q=80",
    featured: false,
    isNew: false,
    isBestseller: true,
  },
  {
    id: "5",
    slug: "react-native-mobile-app",
    title: "React Native Mobile Kit",
    description: "Cross-platform mobile app starter with navigation, authentication, push notifications, and native features.",
    shortDescription: "Cross-platform mobile starter with auth and notifications.",
    price: 59,
    category: "Mobile",
    technologies: ["React Native", "Expo", "TypeScript", "Firebase"],
    rating: 4.6,
    reviewCount: 98,
    downloadCount: 876,
    version: "1.5.0",
    lastUpdated: "2024-11-28",
    author: { name: "FlexStudio Team", avatar: "FS" },
    thumbnail: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=600&h=400&fit=crop&q=80",
    featured: false,
    isNew: true,
    isBestseller: false,
  },
  {
    id: "6",
    slug: "nextjs-blog-cms",
    title: "Next.js Blog & CMS",
    description: "Modern blog with headless CMS integration, MDX support, SEO optimization, and newsletter system.",
    shortDescription: "Blog with CMS, MDX, SEO, and newsletter integration.",
    price: 35,
    category: "CMS",
    technologies: ["Next.js", "MDX", "Sanity", "Tailwind"],
    rating: 4.7,
    reviewCount: 112,
    downloadCount: 1543,
    version: "2.0.0",
    lastUpdated: "2024-11-25",
    author: { name: "FlexStudio Team", avatar: "FS" },
    thumbnail: "https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?w=600&h=400&fit=crop&q=80",
    featured: false,
    isNew: false,
    isBestseller: false,
  },
  {
    id: "7",
    slug: "python-ai-chatbot",
    title: "Python AI Chatbot",
    description: "OpenAI-powered chatbot with conversation history, context management, and web interface.",
    shortDescription: "AI chatbot with OpenAI integration and web UI.",
    price: 29,
    category: "AI",
    technologies: ["Python", "OpenAI", "FastAPI", "React"],
    rating: 4.5,
    reviewCount: 87,
    downloadCount: 654,
    version: "1.2.0",
    lastUpdated: "2024-11-20",
    author: { name: "FlexStudio Team", avatar: "FS" },
    thumbnail: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=600&h=400&fit=crop&q=80",
    featured: false,
    isNew: true,
    isBestseller: false,
  },
  {
    id: "8",
    slug: "saas-invoice-system",
    title: "SaaS Invoice System",
    description: "Complete invoicing solution with PDF generation, email sending, payment tracking, and client portal.",
    shortDescription: "Invoicing system with PDF generation and payments.",
    price: 45,
    category: "SaaS",
    technologies: ["Next.js", "Prisma", "Stripe", "React Email"],
    rating: 4.6,
    reviewCount: 76,
    downloadCount: 543,
    version: "1.4.0",
    lastUpdated: "2024-11-18",
    author: { name: "FlexStudio Team", avatar: "FS" },
    thumbnail: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=600&h=400&fit=crop&q=80",
    featured: false,
    isNew: false,
    isBestseller: false,
  },
  {
    id: "9",
    slug: "graphql-api-boilerplate",
    title: "GraphQL API Boilerplate",
    description: "Production-ready GraphQL API with authentication, subscriptions, file uploads, and Redis caching.",
    shortDescription: "GraphQL API with auth, subscriptions, and caching.",
    price: 42,
    category: "APIs",
    technologies: ["Node.js", "GraphQL", "Prisma", "Redis", "WebSocket"],
    rating: 4.7,
    reviewCount: 64,
    downloadCount: 432,
    version: "1.6.0",
    lastUpdated: "2024-11-15",
    author: { name: "FlexStudio Team", avatar: "FS" },
    thumbnail: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=600&h=400&fit=crop&q=80",
    featured: false,
    isNew: false,
    isBestseller: false,
  },
  {
    id: "10",
    slug: "nextjs-realtime-collab",
    title: "Next.js Realtime Collaboration",
    description: "Real-time collaborative editor with WebSocket, cursor presence, and version history.",
    shortDescription: "Real-time collab editor with WebSocket and presence.",
    price: 89,
    category: "SaaS",
    technologies: ["Next.js", "WebSocket", "Yjs", "PostgreSQL", "Redis"],
    rating: 4.9,
    reviewCount: 45,
    downloadCount: 321,
    version: "1.0.0",
    lastUpdated: "2024-12-12",
    author: { name: "FlexStudio Team", avatar: "FS" },
    thumbnail: "https://images.unsplash.com/photo-1531482615713-2afd69097998?w=600&h=400&fit=crop&q=80",
    featured: false,
    isNew: true,
    isBestseller: false,
  },
  {
    id: "11",
    slug: "vue3-admin-template",
    title: "Vue 3 Admin Template",
    description: "Modern admin template built with Vue 3, Vite, and Pinia. Includes 40+ pages and components.",
    shortDescription: "Vue 3 admin with 40+ pages and Vite.",
    price: 39,
    category: "Dashboards",
    technologies: ["Vue 3", "Vite", "Pinia", "Tailwind", "TypeScript"],
    rating: 4.6,
    reviewCount: 89,
    downloadCount: 987,
    version: "2.1.0",
    lastUpdated: "2024-11-10",
    author: { name: "FlexStudio Team", avatar: "FS" },
    thumbnail: "https://images.unsplash.com/photo-1537432376149-e84978e17846?w=600&h=400&fit=crop&q=80",
    featured: false,
    isNew: false,
    isBestseller: false,
  },
  {
    id: "12",
    slug: "laravel-api-starter",
    title: "Laravel API Starter",
    description: "Complete Laravel API starter with Sanctum auth, rate limiting, API resources, and documentation.",
    shortDescription: "Laravel API with auth, rate limiting, and docs.",
    price: 35,
    category: "APIs",
    technologies: ["Laravel", "PHP", "MySQL", "Sanctum"],
    rating: 4.5,
    reviewCount: 67,
    downloadCount: 765,
    version: "1.8.0",
    lastUpdated: "2024-11-05",
    author: { name: "FlexStudio Team", avatar: "FS" },
    thumbnail: "https://images.unsplash.com/photo-1599946347371-68eb71b16afc?w=600&h=400&fit=crop&q=80",
    featured: false,
    isNew: false,
    isBestseller: false,
  },
];

export const categories = [
  "All",
  "Boilerplates",
  "Dashboards",
  "E-Commerce",
  "APIs",
  "Mobile",
  "CMS",
  "AI",
  "SaaS",
];

export const technologies = [
  "Next.js",
  "React",
  "Vue",
  "Node.js",
  "Python",
  "Laravel",
  "TypeScript",
  "Tailwind",
  "Prisma",
  "Stripe",
];
