export interface Template {
  id: string;
  slug: string;
  title: string;
  description: string;
  shortDescription: string;
  price: number;
  originalPrice?: number;
  category: string;
  technologies: string[];
  rating: number;
  reviewCount: number;
  downloadCount: number;
  version: string;
  lastUpdated: string;
  author: {
    name: string;
    avatar: string;
  };
  thumbnail: string;
  images: string[];
  featured: boolean;
  isNew: boolean;
  isBestseller: boolean;
}

export const templates: Template[] = [
  {
    id: "1",
    slug: "dashboard-pro",
    title: "Dashboard Pro",
    description: "A premium admin dashboard template with 60+ components, multiple layouts, and dark mode. Built with Next.js and Tailwind CSS.",
    shortDescription: "Premium admin dashboard with 60+ components and dark mode.",
    price: 49,
    originalPrice: 79,
    category: "Dashboard",
    technologies: ["Next.js", "TypeScript", "Tailwind", "Recharts"],
    rating: 4.9,
    reviewCount: 312,
    downloadCount: 4521,
    version: "3.2.0",
    lastUpdated: "2024-12-12",
    author: { name: "FlexStudio", avatar: "FS" },
    thumbnail: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=600&fit=crop&q=80",
    images: [
      "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&h=800&fit=crop&q=80",
      "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&h=800&fit=crop&q=80",
    ],
    featured: true,
    isNew: false,
    isBestseller: true,
  },
  {
    id: "2",
    slug: "saas-landing",
    title: "SaaS Landing Page",
    description: "High-converting SaaS landing page with hero, features, pricing, testimonials, and FAQ sections. Optimized for conversions.",
    shortDescription: "High-converting SaaS landing page template.",
    price: 29,
    category: "Landing Page",
    technologies: ["Next.js", "Tailwind", "Framer Motion"],
    rating: 4.8,
    reviewCount: 245,
    downloadCount: 3892,
    version: "2.1.0",
    lastUpdated: "2024-12-10",
    author: { name: "FlexStudio", avatar: "FS" },
    thumbnail: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=600&fit=crop&q=80",
    images: [
      "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&h=800&fit=crop&q=80",
    ],
    featured: true,
    isNew: false,
    isBestseller: true,
  },
  {
    id: "3",
    slug: "portfolio-creative",
    title: "Creative Portfolio",
    description: "Stunning portfolio template for designers and developers. Features unique animations, project showcases, and contact form.",
    shortDescription: "Beautiful portfolio template with unique animations.",
    price: 25,
    category: "Portfolio",
    technologies: ["Next.js", "Tailwind", "Framer Motion", "Three.js"],
    rating: 4.7,
    reviewCount: 189,
    downloadCount: 2876,
    version: "1.8.0",
    lastUpdated: "2024-12-08",
    author: { name: "FlexStudio", avatar: "FS" },
    thumbnail: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=600&fit=crop&q=80",
    images: [],
    featured: true,
    isNew: false,
    isBestseller: false,
  },
  {
    id: "4",
    slug: "ecommerce-starter",
    title: "E-Commerce Starter",
    description: "Complete e-commerce template with product pages, cart, checkout, and admin panel. Stripe integration included.",
    shortDescription: "Full e-commerce template with Stripe integration.",
    price: 59,
    originalPrice: 89,
    category: "E-Commerce",
    technologies: ["Next.js", "TypeScript", "Prisma", "Stripe"],
    rating: 4.8,
    reviewCount: 178,
    downloadCount: 2345,
    version: "2.0.0",
    lastUpdated: "2024-12-05",
    author: { name: "FlexStudio", avatar: "FS" },
    thumbnail: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&h=600&fit=crop&q=80",
    images: [],
    featured: false,
    isNew: false,
    isBestseller: true,
  },
  {
    id: "5",
    slug: "blog-minimal",
    title: "Minimal Blog",
    description: "Clean, minimal blog template with MDX support, syntax highlighting, and newsletter integration.",
    shortDescription: "Clean blog template with MDX and dark mode.",
    price: 19,
    category: "Blog",
    technologies: ["Next.js", "MDX", "Tailwind"],
    rating: 4.6,
    reviewCount: 156,
    downloadCount: 2134,
    version: "1.5.0",
    lastUpdated: "2024-12-01",
    author: { name: "FlexStudio", avatar: "FS" },
    thumbnail: "https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?w=800&h=600&fit=crop&q=80",
    images: [],
    featured: false,
    isNew: false,
    isBestseller: false,
  },
  {
    id: "6",
    slug: "agency-template",
    title: "Agency Template",
    description: "Professional agency website template with services, team, portfolio, and contact pages. Perfect for creative agencies.",
    shortDescription: "Professional template for agencies and studios.",
    price: 35,
    category: "Business",
    technologies: ["Next.js", "Tailwind", "Framer Motion"],
    rating: 4.7,
    reviewCount: 134,
    downloadCount: 1876,
    version: "1.9.0",
    lastUpdated: "2024-11-28",
    author: { name: "FlexStudio", avatar: "FS" },
    thumbnail: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=600&fit=crop&q=80",
    images: [],
    featured: false,
    isNew: true,
    isBestseller: false,
  },
  {
    id: "7",
    slug: "react-components",
    title: "React UI Kit",
    description: "50+ beautifully crafted React components. Accessible, customizable, and built with Tailwind CSS.",
    shortDescription: "50+ React components with Tailwind CSS.",
    price: 39,
    category: "UI Kit",
    technologies: ["React", "TypeScript", "Tailwind", "Storybook"],
    rating: 4.8,
    reviewCount: 198,
    downloadCount: 3210,
    version: "2.3.0",
    lastUpdated: "2024-12-11",
    author: { name: "FlexStudio", avatar: "FS" },
    thumbnail: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&h=600&fit=crop&q=80",
    images: [],
    featured: false,
    isNew: false,
    isBestseller: true,
  },
  {
    id: "8",
    slug: "nextjs-starter",
    title: "Next.js Starter",
    description: "Production-ready Next.js starter with authentication, database, payments, and email. Start building in minutes.",
    shortDescription: "Production-ready Next.js starter kit.",
    price: 45,
    originalPrice: 65,
    category: "Starter",
    technologies: ["Next.js", "TypeScript", "Prisma", "NextAuth"],
    rating: 4.9,
    reviewCount: 167,
    downloadCount: 2543,
    version: "3.0.0",
    lastUpdated: "2024-12-09",
    author: { name: "FlexStudio", avatar: "FS" },
    thumbnail: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&h=600&fit=crop&q=80",
    images: [],
    featured: false,
    isNew: false,
    isBestseller: true,
  },
  {
    id: "9",
    slug: "restaurant-template",
    title: "Restaurant Template",
    description: "Elegant restaurant website template with menu, reservations, gallery, and online ordering integration.",
    shortDescription: "Elegant restaurant template with online ordering.",
    price: 29,
    category: "Business",
    technologies: ["Next.js", "Tailwind", "Framer Motion"],
    rating: 4.5,
    reviewCount: 89,
    downloadCount: 1234,
    version: "1.3.0",
    lastUpdated: "2024-11-25",
    author: { name: "FlexStudio", avatar: "FS" },
    thumbnail: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&h=600&fit=crop&q=80",
    images: [],
    featured: false,
    isNew: false,
    isBestseller: false,
  },
  {
    id: "10",
    slug: "vue-admin",
    title: "Vue Admin Dashboard",
    description: "Modern admin dashboard built with Vue 3 and Vite. Includes 40+ pages, charts, and real-time data.",
    shortDescription: "Vue 3 admin dashboard with 40+ pages.",
    price: 39,
    category: "Dashboard",
    technologies: ["Vue 3", "Vite", "Pinia", "Tailwind"],
    rating: 4.6,
    reviewCount: 112,
    downloadCount: 1567,
    version: "2.0.0",
    lastUpdated: "2024-11-20",
    author: { name: "FlexStudio", avatar: "FS" },
    thumbnail: "https://images.unsplash.com/photo-1537432376149-e84978e17846?w=800&h=600&fit=crop&q=80",
    images: [],
    featured: false,
    isNew: true,
    isBestseller: false,
  },
  {
    id: "11",
    slug: "education-platform",
    title: "Education Platform",
    description: "Online learning platform template with courses, quizzes, progress tracking, and certificates.",
    shortDescription: "Online learning platform with courses and quizzes.",
    price: 49,
    category: "SaaS",
    technologies: ["Next.js", "TypeScript", "Prisma", "Stripe"],
    rating: 4.7,
    reviewCount: 98,
    downloadCount: 1098,
    version: "1.2.0",
    lastUpdated: "2024-11-18",
    author: { name: "FlexStudio", avatar: "FS" },
    thumbnail: "https://images.unsplash.com/photo-1501504905252-473c47e087f8?w=800&h=600&fit=crop&q=80",
    images: [],
    featured: false,
    isNew: true,
    isBestseller: false,
  },
  {
    id: "12",
    slug: "tailwind-components",
    title: "Tailwind UI Components",
    description: "200+ Tailwind CSS components for any project. Copy-paste ready with dark mode support.",
    shortDescription: "200+ copy-paste Tailwind components.",
    price: 25,
    category: "UI Kit",
    technologies: ["Tailwind CSS", "HTML", "JavaScript"],
    rating: 4.7,
    reviewCount: 234,
    downloadCount: 4123,
    version: "3.1.0",
    lastUpdated: "2024-12-13",
    author: { name: "FlexStudio", avatar: "FS" },
    thumbnail: "https://images.unsplash.com/photo-1507721999472-8ed4421c4af2?w=800&h=600&fit=crop&q=80",
    images: [],
    featured: false,
    isNew: false,
    isBestseller: true,
  },
  {
    id: "13",
    slug: "real-estate",
    title: "Real Estate Template",
    description: "Modern real estate listing template with property search, filters, virtual tours, and agent profiles.",
    shortDescription: "Real estate template with property search.",
    price: 35,
    category: "Business",
    technologies: ["Next.js", "Tailwind", "Mapbox"],
    rating: 4.5,
    reviewCount: 76,
    downloadCount: 876,
    version: "1.1.0",
    lastUpdated: "2024-11-15",
    author: { name: "FlexStudio", avatar: "FS" },
    thumbnail: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&h=600&fit=crop&q=80",
    images: [],
    featured: false,
    isNew: false,
    isBestseller: false,
  },
  {
    id: "14",
    slug: "healthcare-portal",
    title: "Healthcare Portal",
    description: "Medical dashboard template with patient management, appointments, and telehealth features.",
    shortDescription: "Healthcare dashboard with patient management.",
    price: 45,
    category: "Dashboard",
    technologies: ["Next.js", "TypeScript", "Tailwind", "Prisma"],
    rating: 4.6,
    reviewCount: 67,
    downloadCount: 654,
    version: "1.0.0",
    lastUpdated: "2024-12-14",
    author: { name: "FlexStudio", avatar: "FS" },
    thumbnail: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&h=600&fit=crop&q=80",
    images: [],
    featured: false,
    isNew: true,
    isBestseller: false,
  },
  {
    id: "15",
    slug: "fitness-app",
    title: "Fitness App Template",
    description: "Fitness tracking app template with workout plans, progress charts, and social features.",
    shortDescription: "Fitness app with workouts and progress tracking.",
    price: 29,
    category: "Mobile",
    technologies: ["React Native", "Expo", "TypeScript"],
    rating: 4.5,
    reviewCount: 54,
    downloadCount: 543,
    version: "1.2.0",
    lastUpdated: "2024-11-12",
    author: { name: "FlexStudio", avatar: "FS" },
    thumbnail: "https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=800&h=600&fit=crop&q=80",
    images: [],
    featured: false,
    isNew: false,
    isBestseller: false,
  },
  {
    id: "16",
    slug: "ai-dashboard",
    title: "AI Dashboard",
    description: "AI-powered dashboard template with chat interface, analytics, and model management.",
    shortDescription: "AI dashboard with chat and analytics.",
    price: 55,
    category: "Dashboard",
    technologies: ["Next.js", "TypeScript", "Tailwind", "OpenAI"],
    rating: 4.8,
    reviewCount: 89,
    downloadCount: 1234,
    version: "1.3.0",
    lastUpdated: "2024-12-07",
    author: { name: "FlexStudio", avatar: "FS" },
    thumbnail: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&h=600&fit=crop&q=80",
    images: [],
    featured: false,
    isNew: true,
    isBestseller: false,
  },
];

export const templateCategories = [
  "All",
  "Dashboard",
  "Landing Page",
  "Portfolio",
  "E-Commerce",
  "Blog",
  "Business",
  "UI Kit",
  "Starter",
  "SaaS",
  "Mobile",
];

export const templateTechnologies = [
  "Next.js",
  "React",
  "Vue",
  "Tailwind",
  "TypeScript",
  "Framer Motion",
  "Prisma",
  "Stripe",
];
