import "dotenv/config";
import { PrismaClient } from "../src/generated/prisma/client";
import { PrismaNeon } from "@prisma/adapter-neon";
import bcrypt from "bcryptjs";

const adapter = new PrismaNeon({
  connectionString: process.env.DATABASE_URL!,
});

const prisma = new PrismaClient({ adapter }) as any;

async function main() {
  console.log("Seeding database...");

  // Create primary admin user
  const adminPassword = await bcrypt.hash("admin123", 12);
  const admin = await prisma.user.upsert({
    where: { email: "flexstudio@kauxync.in" },
    update: { role: "super_admin", name: "FlexStudio Admin" },
    create: {
      name: "FlexStudio Admin",
      email: "flexstudio@kauxync.in",
      password: adminPassword,
      role: "super_admin",
    },
  });
  console.log(`Created primary admin: ${admin.email}`);

  // Create legacy admin alias
  await prisma.user.upsert({
    where: { email: "admin@flexstudio.dev" },
    update: { role: "admin", name: "FlexStudio Admin" },
    create: {
      name: "FlexStudio Admin",
      email: "admin@flexstudio.dev",
      password: adminPassword,
      role: "admin",
    },
  });

  // Create demo user
  const demoPassword = await bcrypt.hash("demo123", 12);
  const demoUser = await prisma.user.upsert({
    where: { email: "demo@flexstudio.dev" },
    update: { name: "Demo User" },
    create: {
      name: "Demo User",
      email: "demo@flexstudio.dev",
      password: demoPassword,
      role: "user",
    },
  });
  console.log(`Created demo user: ${demoUser.email}`);

  // =====================
  // Templates
  // =====================
  const templates = [
    {
      slug: "dashboard-pro",
      title: "Dashboard Pro",
      description: "A premium admin dashboard template with 60+ components, multiple layouts, and dark mode. Built with Next.js and Tailwind CSS.",
      shortDesc: "Premium admin dashboard with 60+ components and dark mode.",
      price: 49,
      originalPrice: 79,
      type: "template",
      category: "Dashboard",
      technologies: ["Next.js", "TypeScript", "Tailwind", "Recharts"],
      rating: 4.9,
      reviewCount: 312,
      downloadCount: 4521,
      version: "3.2.0",
      thumbnail: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=600&fit=crop&q=80",
      images: ["https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&h=800&fit=crop&q=80"],
      featured: true,
      isNew: false,
      isBestseller: true,
      authorId: admin.id,
    },
    {
      slug: "saas-landing",
      title: "SaaS Landing Page",
      description: "High-converting SaaS landing page with hero, features, pricing, testimonials, and FAQ sections.",
      shortDesc: "High-converting SaaS landing page template.",
      price: 29,
      type: "template",
      category: "Landing Page",
      technologies: ["Next.js", "Tailwind", "Framer Motion"],
      rating: 4.8,
      reviewCount: 245,
      downloadCount: 3892,
      version: "2.1.0",
      thumbnail: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=600&fit=crop&q=80",
      images: [],
      featured: true,
      isNew: false,
      isBestseller: true,
      authorId: admin.id,
    },
    {
      slug: "portfolio-creative",
      title: "Creative Portfolio",
      description: "Stunning portfolio template for designers and developers. Features unique animations, project showcases, and contact form.",
      shortDesc: "Beautiful portfolio template with unique animations.",
      price: 25,
      type: "template",
      category: "Portfolio",
      technologies: ["Next.js", "Tailwind", "Framer Motion", "Three.js"],
      rating: 4.7,
      reviewCount: 189,
      downloadCount: 2876,
      version: "1.8.0",
      thumbnail: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=600&fit=crop&q=80",
      images: [],
      featured: true,
      isNew: false,
      isBestseller: false,
      authorId: admin.id,
    },
    {
      slug: "ecommerce-starter",
      title: "E-Commerce Starter",
      description: "Complete e-commerce template with product pages, cart, checkout, and admin panel. Stripe integration included.",
      shortDesc: "Full e-commerce template with Stripe integration.",
      price: 59,
      originalPrice: 89,
      type: "template",
      category: "E-Commerce",
      technologies: ["Next.js", "TypeScript", "Prisma", "Stripe"],
      rating: 4.8,
      reviewCount: 178,
      downloadCount: 2345,
      version: "2.0.0",
      thumbnail: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&h=600&fit=crop&q=80",
      images: [],
      featured: false,
      isNew: false,
      isBestseller: true,
      authorId: admin.id,
    },
    {
      slug: "blog-minimal",
      title: "Minimal Blog",
      description: "Clean, minimal blog template with MDX support, syntax highlighting, and newsletter integration.",
      shortDesc: "Clean blog template with MDX and dark mode.",
      price: 19,
      type: "template",
      category: "Blog",
      technologies: ["Next.js", "MDX", "Tailwind"],
      rating: 4.6,
      reviewCount: 156,
      downloadCount: 2134,
      version: "1.5.0",
      thumbnail: "https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?w=800&h=600&fit=crop&q=80",
      images: [],
      featured: false,
      isNew: false,
      isBestseller: false,
      authorId: admin.id,
    },
    {
      slug: "agency-template",
      title: "Agency Template",
      description: "Professional agency website template with services, team, portfolio, and contact pages.",
      shortDesc: "Professional template for agencies and studios.",
      price: 35,
      type: "template",
      category: "Business",
      technologies: ["Next.js", "Tailwind", "Framer Motion"],
      rating: 4.7,
      reviewCount: 134,
      downloadCount: 1876,
      version: "1.9.0",
      thumbnail: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=600&fit=crop&q=80",
      images: [],
      featured: false,
      isNew: true,
      isBestseller: false,
      authorId: admin.id,
    },
    {
      slug: "react-components",
      title: "React UI Kit",
      description: "50+ beautifully crafted React components. Accessible, customizable, and built with Tailwind CSS.",
      shortDesc: "50+ React components with Tailwind CSS.",
      price: 39,
      type: "template",
      category: "UI Kit",
      technologies: ["React", "TypeScript", "Tailwind", "Storybook"],
      rating: 4.8,
      reviewCount: 198,
      downloadCount: 3210,
      version: "2.3.0",
      thumbnail: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&h=600&fit=crop&q=80",
      images: [],
      featured: false,
      isNew: false,
      isBestseller: true,
      authorId: admin.id,
    },
    {
      slug: "nextjs-starter",
      title: "Next.js Starter",
      description: "Production-ready Next.js starter with authentication, database, payments, and email.",
      shortDesc: "Production-ready Next.js starter kit.",
      price: 45,
      originalPrice: 65,
      type: "template",
      category: "Starter",
      technologies: ["Next.js", "TypeScript", "Prisma", "NextAuth"],
      rating: 4.9,
      reviewCount: 167,
      downloadCount: 2543,
      version: "3.0.0",
      thumbnail: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&h=600&fit=crop&q=80",
      images: [],
      featured: false,
      isNew: false,
      isBestseller: true,
      authorId: admin.id,
    },
    {
      slug: "restaurant-template",
      title: "Restaurant Template",
      description: "Elegant restaurant website template with menu, reservations, gallery, and online ordering.",
      shortDesc: "Elegant restaurant template with online ordering.",
      price: 29,
      type: "template",
      category: "Business",
      technologies: ["Next.js", "Tailwind", "Framer Motion"],
      rating: 4.5,
      reviewCount: 89,
      downloadCount: 1234,
      version: "1.3.0",
      thumbnail: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&h=600&fit=crop&q=80",
      images: [],
      featured: false,
      isNew: false,
      isBestseller: false,
      authorId: admin.id,
    },
    {
      slug: "vue-admin",
      title: "Vue Admin Dashboard",
      description: "Modern admin dashboard built with Vue 3 and Vite. Includes 40+ pages, charts, and real-time data.",
      shortDesc: "Vue 3 admin dashboard with 40+ pages.",
      price: 39,
      type: "template",
      category: "Dashboard",
      technologies: ["Vue 3", "Vite", "Pinia", "Tailwind"],
      rating: 4.6,
      reviewCount: 112,
      downloadCount: 1567,
      version: "2.0.0",
      thumbnail: "https://images.unsplash.com/photo-1537432376149-e84978e17846?w=800&h=600&fit=crop&q=80",
      images: [],
      featured: false,
      isNew: true,
      isBestseller: false,
      authorId: admin.id,
    },
    {
      slug: "education-platform",
      title: "Education Platform",
      description: "Online learning platform template with courses, quizzes, progress tracking, and certificates.",
      shortDesc: "Online learning platform with courses and quizzes.",
      price: 49,
      type: "template",
      category: "SaaS",
      technologies: ["Next.js", "TypeScript", "Prisma", "Stripe"],
      rating: 4.7,
      reviewCount: 98,
      downloadCount: 1098,
      version: "1.2.0",
      thumbnail: "https://images.unsplash.com/photo-1501504905252-473c47e087f8?w=800&h=600&fit=crop&q=80",
      images: [],
      featured: false,
      isNew: true,
      isBestseller: false,
      authorId: admin.id,
    },
    {
      slug: "tailwind-components",
      title: "Tailwind UI Components",
      description: "200+ Tailwind CSS components for any project. Copy-paste ready with dark mode support.",
      shortDesc: "200+ copy-paste Tailwind components.",
      price: 25,
      type: "template",
      category: "UI Kit",
      technologies: ["Tailwind CSS", "HTML", "JavaScript"],
      rating: 4.7,
      reviewCount: 234,
      downloadCount: 4123,
      version: "3.1.0",
      thumbnail: "https://images.unsplash.com/photo-1507721999472-8ed4421c4af2?w=800&h=600&fit=crop&q=80",
      images: [],
      featured: false,
      isNew: false,
      isBestseller: true,
      authorId: admin.id,
    },
  ];

  for (const template of templates) {
    await prisma.product.upsert({
      where: { slug: template.slug },
      update: template,
      create: template,
    });
  }
  console.log(`Created ${templates.length} templates`);

  // =====================
  // Source Code Products
  // =====================
  const sourceCode = [
    {
      slug: "nextjs-saas-starter",
      title: "Next.js SaaS Starter Kit",
      description: "A production-ready SaaS boilerplate with authentication, billing, dashboard, and more.",
      shortDesc: "Full-featured SaaS boilerplate with auth, billing, and dashboard.",
      price: 79,
      originalPrice: 129,
      type: "source-code",
      category: "Boilerplates",
      technologies: ["Next.js", "TypeScript", "Prisma", "Stripe", "Tailwind"],
      rating: 4.9,
      reviewCount: 234,
      downloadCount: 1847,
      version: "2.1.0",
      thumbnail: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=600&h=400&fit=crop&q=80",
      images: [],
      featured: true,
      isNew: false,
      isBestseller: true,
      authorId: admin.id,
    },
    {
      slug: "react-dashboard-admin",
      title: "React Dashboard Admin Pro",
      description: "A comprehensive admin dashboard with 50+ components, charts, tables, and real-time data visualization.",
      shortDesc: "Complete admin dashboard with 50+ UI components and charts.",
      price: 49,
      type: "source-code",
      category: "Dashboards",
      technologies: ["React", "TypeScript", "Recharts", "Tailwind"],
      rating: 4.8,
      reviewCount: 189,
      downloadCount: 2341,
      version: "3.0.2",
      thumbnail: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&h=400&fit=crop&q=80",
      images: [],
      featured: true,
      isNew: false,
      isBestseller: true,
      authorId: admin.id,
    },
    {
      slug: "nextjs-ecommerce-store",
      title: "Next.js E-Commerce Store",
      description: "Full-featured e-commerce solution with product management, cart, checkout, and Stripe integration.",
      shortDesc: "Complete e-commerce solution with Stripe payments.",
      price: 69,
      originalPrice: 99,
      type: "source-code",
      category: "E-Commerce",
      technologies: ["Next.js", "TypeScript", "Stripe", "Prisma", "PostgreSQL"],
      rating: 4.7,
      reviewCount: 156,
      downloadCount: 1293,
      version: "1.8.0",
      thumbnail: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=600&h=400&fit=crop&q=80",
      images: [],
      featured: true,
      isNew: false,
      isBestseller: false,
      authorId: admin.id,
    },
    {
      slug: "nodejs-rest-api",
      title: "Node.js REST API Starter",
      description: "Production-ready REST API with authentication, rate limiting, caching, and comprehensive documentation.",
      shortDesc: "Robust REST API with auth, caching, and documentation.",
      price: 39,
      type: "source-code",
      category: "APIs",
      technologies: ["Node.js", "Express", "MongoDB", "Redis", "JWT"],
      rating: 4.8,
      reviewCount: 142,
      downloadCount: 1876,
      version: "2.3.1",
      thumbnail: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=600&h=400&fit=crop&q=80",
      images: [],
      featured: false,
      isNew: false,
      isBestseller: true,
      authorId: admin.id,
    },
    {
      slug: "react-native-mobile-app",
      title: "React Native Mobile Kit",
      description: "Cross-platform mobile app starter with navigation, authentication, push notifications, and native features.",
      shortDesc: "Cross-platform mobile starter with auth and notifications.",
      price: 59,
      type: "source-code",
      category: "Mobile",
      technologies: ["React Native", "Expo", "TypeScript", "Firebase"],
      rating: 4.6,
      reviewCount: 98,
      downloadCount: 876,
      version: "1.5.0",
      thumbnail: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=600&h=400&fit=crop&q=80",
      images: [],
      featured: false,
      isNew: true,
      isBestseller: false,
      authorId: admin.id,
    },
    {
      slug: "nextjs-blog-cms",
      title: "Next.js Blog & CMS",
      description: "Modern blog with headless CMS integration, MDX support, SEO optimization, and newsletter system.",
      shortDesc: "Blog with CMS, MDX, SEO, and newsletter integration.",
      price: 35,
      type: "source-code",
      category: "CMS",
      technologies: ["Next.js", "MDX", "Sanity", "Tailwind"],
      rating: 4.7,
      reviewCount: 112,
      downloadCount: 1543,
      version: "2.0.0",
      thumbnail: "https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?w=600&h=400&fit=crop&q=80",
      images: [],
      featured: false,
      isNew: false,
      isBestseller: false,
      authorId: admin.id,
    },
    {
      slug: "python-ai-chatbot",
      title: "Python AI Chatbot",
      description: "OpenAI-powered chatbot with conversation history, context management, and web interface.",
      shortDesc: "AI chatbot with OpenAI integration and web UI.",
      price: 29,
      type: "source-code",
      category: "AI",
      technologies: ["Python", "OpenAI", "FastAPI", "React"],
      rating: 4.5,
      reviewCount: 87,
      downloadCount: 654,
      version: "1.2.0",
      thumbnail: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=600&h=400&fit=crop&q=80",
      images: [],
      featured: false,
      isNew: true,
      isBestseller: false,
      authorId: admin.id,
    },
    {
      slug: "saas-invoice-system",
      title: "SaaS Invoice System",
      description: "Complete invoicing solution with PDF generation, email sending, payment tracking, and client portal.",
      shortDesc: "Invoicing system with PDF generation and payments.",
      price: 45,
      type: "source-code",
      category: "SaaS",
      technologies: ["Next.js", "Prisma", "Stripe", "React Email"],
      rating: 4.6,
      reviewCount: 76,
      downloadCount: 543,
      version: "1.4.0",
      thumbnail: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=600&h=400&fit=crop&q=80",
      images: [],
      featured: false,
      isNew: false,
      isBestseller: false,
      authorId: admin.id,
    },
    {
      slug: "graphql-api-boilerplate",
      title: "GraphQL API Boilerplate",
      description: "Production-ready GraphQL API with authentication, subscriptions, file uploads, and Redis caching.",
      shortDesc: "GraphQL API with auth, subscriptions, and caching.",
      price: 42,
      type: "source-code",
      category: "APIs",
      technologies: ["Node.js", "GraphQL", "Prisma", "Redis", "WebSocket"],
      rating: 4.7,
      reviewCount: 64,
      downloadCount: 432,
      version: "1.6.0",
      thumbnail: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=600&h=400&fit=crop&q=80",
      images: [],
      featured: false,
      isNew: false,
      isBestseller: false,
      authorId: admin.id,
    },
    {
      slug: "nextjs-realtime-collab",
      title: "Next.js Realtime Collaboration",
      description: "Real-time collaborative editor with WebSocket, cursor presence, and version history.",
      shortDesc: "Real-time collab editor with WebSocket and presence.",
      price: 89,
      type: "source-code",
      category: "SaaS",
      technologies: ["Next.js", "WebSocket", "Yjs", "PostgreSQL", "Redis"],
      rating: 4.9,
      reviewCount: 45,
      downloadCount: 321,
      version: "1.0.0",
      thumbnail: "https://images.unsplash.com/photo-1531482615713-2afd69097998?w=600&h=400&fit=crop&q=80",
      images: [],
      featured: false,
      isNew: true,
      isBestseller: false,
      authorId: admin.id,
    },
    {
      slug: "vue3-admin-template",
      title: "Vue 3 Admin Template",
      description: "Modern admin template built with Vue 3, Vite, and Pinia. Includes 40+ pages and components.",
      shortDesc: "Vue 3 admin with 40+ pages and Vite.",
      price: 39,
      type: "source-code",
      category: "Dashboards",
      technologies: ["Vue 3", "Vite", "Pinia", "Tailwind", "TypeScript"],
      rating: 4.6,
      reviewCount: 89,
      downloadCount: 987,
      version: "2.1.0",
      thumbnail: "https://images.unsplash.com/photo-1537432376149-e84978e17846?w=600&h=400&fit=crop&q=80",
      images: [],
      featured: false,
      isNew: false,
      isBestseller: false,
      authorId: admin.id,
    },
    {
      slug: "laravel-api-starter",
      title: "Laravel API Starter",
      description: "Complete Laravel API starter with Sanctum auth, rate limiting, API resources, and documentation.",
      shortDesc: "Laravel API with auth, rate limiting, and docs.",
      price: 35,
      type: "source-code",
      category: "APIs",
      technologies: ["Laravel", "PHP", "MySQL", "Sanctum"],
      rating: 4.5,
      reviewCount: 67,
      downloadCount: 765,
      version: "1.8.0",
      thumbnail: "https://images.unsplash.com/photo-1599946347371-68eb71b16afc?w=600&h=400&fit=crop&q=80",
      images: [],
      featured: false,
      isNew: false,
      isBestseller: false,
      authorId: admin.id,
    },
  ];

  for (const product of sourceCode) {
    await prisma.product.upsert({
      where: { slug: product.slug },
      update: product,
      create: product,
    });
  }
  console.log(`Created ${sourceCode.length} source code products`);



  // =====================
  // Sample Reviews
  // =====================
  const sampleReviews = [
    { userId: demoUser.id, productId: (await prisma.product.findUnique({ where: { slug: "dashboard-pro" } }))?.id, rating: 5, comment: "Excellent template! Clean code, great documentation, and the support team is very responsive.", verified: true, helpful: 24 },
    { userId: demoUser.id, productId: (await prisma.product.findUnique({ where: { slug: "saas-landing" } }))?.id, rating: 5, comment: "Beautiful design and very easy to customize. Highly recommended!", verified: true, helpful: 18 },
  ];

  for (const review of sampleReviews) {
    if (review.productId) {
      await prisma.review.upsert({
        where: { userId_productId: { userId: review.userId, productId: review.productId } },
        update: review,
        create: review,
      });
    }
  }
  console.log("Created sample reviews");

  console.log("Seeding complete!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
